default_settings: null
behaviors:
  Car_CAM_NO-STATE_V3_8B:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 51200
      learning_rate: 1e-5
      beta: 1e-2
      epsilon: 0.1
      lambd: 0.975
      num_epoch: 3
      shared_critic: true
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: nature_cnn
      memory:
        memory_size: 256
        sequence_length: 64
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      curiosity:
        gamma: 0.999
        strength: 0.075
        learning_rate: 1e-5
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 3
          vis_encode_type: resnet
          goal_conditioning_type: hyper
          deterministic: false
      extrinsic:
        gamma: 0.999
        strength: 0.1
        network_settings:
          normalize: true
          hidden_units: 512
          num_layers: 4
          vis_encode_type: nature_cnn
          memory:
            memory_size: 256
            sequence_length: 64
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 1
    checkpoint_interval: 200000
    max_steps: 10000000
    time_horizon: 5120
    summary_freq: 10000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 20
  restarts_rate_limit_n: 5
  restarts_rate_limit_period_s: 3500
engine_settings:
  width: 72
  height: 72
  quality_level: 0
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: ppo
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cpu
debug: true
